default: &default
  adapter: mysql2
  encoding: utf8
  host: <%= ENV["DATABASE_HOSTNAME"] %>
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: redeem_card_development

test:
  <<: *default
  database: redeem_card_test

production:
  <<: *default
  database: redeem_card_production
